site_name: CARLA ScenarioRunner
repo_url: https://github.com/carla-simulator/scenario_runner
docs_dir: Docs
edit_uri: 'edit/master/Docs/'
theme: readthedocs
extra_css: [extra.css]

nav:
- Home: index.md
- Quick start:
  - Get ScenarioRunner: getting_scenariorunner.md
  - First steps: getting_started.md
- OpenSCENARIO:
  - OpenSCENARIO support: openscenario_support.md
- FAQ: FAQ.md
- Release Notes: CHANGELOG.md

markdown_extensions:
  - admonition
  - markdown_include.include:
      base_path: '.'

