name: Docker

on: [push, pull_request]

jobs:

  create-image:
    name: create docker image
    runs-on: self-hosted
    steps:
      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        name: Build and push
        with:
          push: true
          file: docker/Dockerfile
          tags: cgellerac/carla-scenario-runner
